apiVersion: v1
kind: Pod
metadata:
  name: webapps-pod-secret
spec:
  volumes:
    - name: webapps-secret
      secret:
        secretName: webapps-secret
  containers:
    - name: secret-container
      image: nginx
      volumeMounts:
        - name: webapps-secret
          mountPath: "/etc/secret-volume"