apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myapplication
spec:
  type: NodePort
  selector:
    app: myapplication
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32098