apiVersion: v1 
kind: Service
metadata:
  name: webapps-service
  labels: 
    app: frontend-webapps
spec:
  type: NodePort
  selector:
    app: frontend-webapps
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32097
