apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jaladeesh@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: ap-south-1
          hostedZoneID: Z07801563EGDZFNSC3UIC
          accessKeyID: AKIAZI2LJC74KTREZWPV
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
