apiVersion: v1
kind: Pod
metadata:
  name: resourepod
spec:
  containers:
  - name: container1
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  - name: container2
    image: kodekloud/webapp-color
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "400m"