apiVersion: v1
kind: Pod
metadata: 
  name: livenessprobe
spec:
  containers:
  - name: livenessprobecontainer
    image: busybox
    args:
    - /bin/sh
    - -c 
    - 'while true; do touch /tmp/heartbeat.txt; sleep 40; done;'
    livenessProbe:
      exec:
        command:
          - test 'find /tmp/heartbeat.txt -mmin -1'
      initialDelaySeconds: 5
      periodSeconds: 8