apiVersion: apps/v1
kind: Deployment
metadata:
  name: greendeployment
  labels:
    app: green 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      name: greenpod
      labels:
        app: green 
    spec:
      containers:
      - name: greencontainer
        image: nginx
      tolerations:
      - key: color
        value: green
        effect: NoSchedule
        operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - green